name: Docker

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
      - "README/*.png"
      - "README/*.svg"
      - "README/*.jpeg"
      - "README/*.jpg"
      - "README/*.md"
      - "LICENSE"
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "README.md"
      - "README/*.png"
      - "README/*.svg"
      - "README/*.jpeg"
      - "README/*.jpg"
      - "README/*.md"
      - "LICENSE"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Clone FoodManager-Backend repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: build_${{ github.sha }}
        if: github.event_name == 'pull_request'

      - name: Push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:0.0.2_${{ github.run_number }}
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
