name: Docker Build

on:
  pull_request:
    branches: [main, stage, develop]
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "README.md"

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:0.0.2-build_${{ github.run_number }}
