name: Build

on:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "README.md"
      - "README/*.png"
      - "README/*.svg"
      - "README/*.jpeg"
      - "README/*.jpg"
      - "README/*.md"
      - "LICENSE"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone FoodManager-Backend repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore --interactive
        working-directory: FoodManagerApi

      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: FoodManagerApi

      - name: Publish build artifact (Linux)
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/Build_Linux -r linux-x64 --self-contained false
        working-directory: FoodManagerApi

      - name: Upload artifact (Linux)
        uses: actions/upload-artifact@v3
        with:
          name: Linux-artifact-#${{ github.run_number }}-${{ github.sha }}
          path: ${{env.DOTNET_ROOT}}/Build_Linux

      - name: Publish build artifact (Windows)
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/Build_Windows -r win10-x64 --self-contained false
        working-directory: FoodManagerApi

      - name: Upload artifact (Windows)
        uses: actions/upload-artifact@v3
        with:
          name: Windows-artifact-#${{ github.run_number }}-${{ github.sha }}
          path: ${{env.DOTNET_ROOT}}/Build_Windows
