# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test

on:
  push:
    branches: [main, stage, develop]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [main, stage, develop]
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone FoodManager-Backend repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore
        working-directory: FoodManagerApi

      - name: Build
        run: dotnet build
        working-directory: FoodManagerApi

      # - name: Test
      #   run: dotnet test --no-build --verbosity normal
      #   working-directory: FoodManagerTest

      - name: dotnet publish
        run: dotnet publish -c Release -o /home/runner/work/FoodManager-Backend/FoodManager-Backend/FoodManagerApi/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: Artifact-$GITHUB_RUN_NUMBER
          path: /home/runner/work/FoodManager-Backend/FoodManager-Backend/FoodManagerApi/FoodManagerApi/bin/Release/
