name: Build and Test

on:
  push:
    branches: [main, stage, develop]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [main, stage, develop]
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "README.md"

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone FoodManager-Backend repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Format code style
        run: dotnet format --verbosity normal

      - name: Restore dependencies
        run: dotnet restore --interactive
        working-directory: FoodManagerApi

      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: FoodManagerApi

      # - name: Test
      #   run: dotnet test --no-build --verbosity normal
      #   working-directory: FoodManagerTest

      - name: Publish build artifact (Linux)
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/Build_Linux -r linux-x64 --self-contained false
        working-directory: FoodManagerApi

      - name: Upload artifact (Linux)
        uses: actions/upload-artifact@v3
        with:
          name: Linux-artifact-#${{ github.run_number }}-${{ github.sha }}
          path: ${{env.DOTNET_ROOT}}/Build_Linux

      - name: Publish build artifact (Windows)
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/Build_Windows -r win10-x64 --self-contained false
        working-directory: FoodManagerApi

      - name: Upload artifact (Windows)
        uses: actions/upload-artifact@v3
        with:
          name: Windows-artifact-#${{ github.run_number }}-${{ github.sha }}
          path: ${{env.DOTNET_ROOT}}/Build_Windows
