name: Sonarcloud analysis

on:
  pull_request:
    branches: [main, stage, develop]
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "README.md"

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Clone FoodManager-Backend repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
